@local=http://localhost:3000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2VlNmM0MDgxMjUxMTgwZjNiZDE1MmUiLCJiaXoiOnRydWUsImlhdCI6MTY3NjU2OTY2OH0.LZ9nRUUblLJAy7CRw01WC51Hc10ZYKB52lp-aRK4ULQ

### register a new user, Question 1
POST {{local}}/users/
Content-Type: application/json

{
    "name": "OfirBizaaa", 
    "email": "OfirBizaaa@gmail.com",
    "password": "gjkmodlas", 
    "biz": true
}

### authenticate (login) an existing user, Question 2
POST {{local}}/auth
Content-Type: application/json

{
    "email":"OfirBizaaa@gmail.com",
    "password": "gjkmodlas"
}

### get logged in user's information, Question 3
GET {{local}}/users/me
x-auth-token: {{token}}

### create new card, Question 4
POST {{local}}/cards/
x-auth-token: {{token}}
Content-Type: application/json

{
"bizName": "Cards",
"bizDescription": "Game cards",
"bizAddress": "Lehavim Lehavim",
"bizPhone": "0501234567",
"bizImage": "https://i.imgur.com/QYP8RJ2.png"
}

### find card by id, Question 5
GET {{local}}/cards/63edebb44f39580a9d99b49a
x-auth-token:{{token}}
Content-Type: application/json



### update card by id, Question 6
PUT {{local}}/cards/63edebb44f39580a9d99b49a
x-auth-token:{{token}}
Content-Type: application/json

{  
    "bizName":"updated",
    "bizAddress":"new Addres",
    "bizPhone":"0525381648",
    "bizDescription":"UPDATEEEEEEEEEEEE",
    "bizImage":"https://i.imgur.com/newwwww.png"
}

### delete card, Question 7
DELETE  {{local}}/cards/63edebb24f39580a9d99b48e
x-auth-token:{{token}}
Content-Type: application/json

### get all user cards, Question 8
GET {{local}}/users/cards
x-auth-token:{{token}}
Content-Type: application/json
